#!/bin/bash

echo "🚂 Deploying ComplianceBot to Railway..."
echo ""
echo "📋 Prerequisites:"
echo "   1. Railway account (free at railway.app)"
echo "   2. GitHub repository with your code"
echo "   3. Environment variables ready"
echo ""
echo "🚀 Deployment Steps:"
echo ""
echo "1. Go to railway.app and create a new project"
echo "2. Connect your GitHub repository"
echo "3. Add these environment variables:"
echo ""
echo "   HUBSPOT_TOKEN=pat-na1-your-token-here"
echo "   OPENAI_API_KEY=sk-your-openai-key-here"
echo "   SLACK_WEBHOOK_URL=https://hooks.slack.com/services/..."
echo "   PROPERTY_LANDING_URL=landing_page_url"
echo "   POLL_INTERVAL=86400000"
echo "   PORT=3000"
echo ""
echo "4. Railway will automatically:"
echo "   ✅ Install dependencies"
echo "   ✅ Install Playwright browsers"
echo "   ✅ Start the daily scheduler"
echo "   ✅ Run continuously"
echo ""
echo "5. Monitor in Railway dashboard:"
echo "   📊 View logs and metrics"
echo "   🔍 Check health status"
echo "   📈 Monitor performance"
echo ""
echo "🎉 Your ComplianceBot will run autonomously!"
echo "   🔍 Checks HubSpot daily for new tickets"
echo "   🚀 Processes compliance automatically"
echo "   📱 Sends Slack notifications for violations"
echo "   📊 Logs everything for audit trail"
echo ""
echo "💰 Cost: Free tier is perfect for daily compliance checking"
